env:
  browser: true
  es2020: true
extends:
  - plugin:react/recommended
  - google
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
  - prettier/@typescript-eslint
  - prettier/react
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - import
  - prefer-arrow
  - react
  - react-hooks
  - prettier
rules: 
  react/prop-types: off
  "@typescript-eslint/explicit-module-boundary-types": "off"
  prefer-arrow/prefer-arrow-functions:
    - error
    - disallowPrototype: true
      singleReturnOnly: false
      classPropertiesAllowed: false
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      argsIgnorePattern: _
      ignoreRestSiblings: false
      varsIgnorePattern: _
  prettier/prettier: error
settings:
  react: 
    version: detect
  import/resolver:
    node:
      paths:
        - assets
      extensions:
        - .js
        - .jsx
        - .json
        - .ts
        - .tsx
