env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
  - prettier/@typescript-eslint
  - prettier/react
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - import
  - prefer-arrow
  - react
  - react-hooks
  - prettier
rules: 
  react/prop-types: off
settings:
  react: 
    version: detect
  import/resolver:
    node:
      paths:
        - assets
      extensions:
        - .js
        - .jsx
        - .json
        - .ts
        - .tsx
